spring.jpa.show-sql=false
spring.jpa.open-in-view=false

app.cookie.secure=true
app.cookie.same-site=None

server.forward-headers-strategy=framework

supabase.url=${SUPABASE_URL}
supabase.secret-key=${SUPABASE_SECRET_KEY}
supabase.storage.bucket=${SUPABASE_STORAGE_BUCKET:documents}