--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Debian 18.6-1.pgdg12+2)
-- Dumped by pg_dump version 18.6 (Debian 18.6-1.pgdg12+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: document; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document (
    document_id bigint NOT NULL,
    content_type character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    file_size bigint NOT NULL,
    original_file_name character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    storage_key character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    knowledge_base_id bigint NOT NULL,
    CONSTRAINT document_status_check CHECK (((status)::text = ANY ((ARRAY['UPLOADED'::character varying, 'PROCESSING'::character varying, 'READY'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: document_chunk; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_chunk (
    chunk_id bigint NOT NULL,
    chunk_index integer NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone,
    document_id bigint NOT NULL,
    embedding public.vector(768)
);


--
-- Name: document_chunk_chunk_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.document_chunk ALTER COLUMN chunk_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.document_chunk_chunk_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: document_document_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.document ALTER COLUMN document_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.document_document_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: knowledge_base; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.knowledge_base (
    knowledge_base_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(255),
    name character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    organization_id bigint NOT NULL
);


--
-- Name: knowledge_base_knowledge_base_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.knowledge_base ALTER COLUMN knowledge_base_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.knowledge_base_knowledge_base_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: membership; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.membership (
    membership_id bigint NOT NULL,
    joined_at timestamp(6) without time zone,
    role character varying(255) NOT NULL,
    organization_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT membership_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'MEMBER'::character varying])::text[])))
);


--
-- Name: membership_membership_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.membership ALTER COLUMN membership_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.membership_membership_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: organization; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.organization (
    organization_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    organization_name character varying(255) NOT NULL,
    status character varying(255),
    updated_at timestamp(6) without time zone,
    CONSTRAINT organization_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'SUSPENDED'::character varying, 'DEACTIVATED'::character varying])::text[])))
);


--
-- Name: organization_organization_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.organization ALTER COLUMN organization_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.organization_organization_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    status character varying(255),
    updated_at timestamp(6) without time zone,
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'SUSPENDED'::character varying])::text[])))
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: document_chunk document_chunk_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_chunk
    ADD CONSTRAINT document_chunk_pkey PRIMARY KEY (chunk_id);


--
-- Name: document document_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document
    ADD CONSTRAINT document_pkey PRIMARY KEY (document_id);


--
-- Name: knowledge_base knowledge_base_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.knowledge_base
    ADD CONSTRAINT knowledge_base_pkey PRIMARY KEY (knowledge_base_id);


--
-- Name: membership membership_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership
    ADD CONSTRAINT membership_pkey PRIMARY KEY (membership_id);


--
-- Name: organization organization_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization
    ADD CONSTRAINT organization_pkey PRIMARY KEY (organization_id);


--
-- Name: knowledge_base ukbl1n1m0oac8bk684tmh377847; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.knowledge_base
    ADD CONSTRAINT ukbl1n1m0oac8bk684tmh377847 UNIQUE (organization_id, name);


--
-- Name: document ukeiidawsj9c12638rt32lyrhfi; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document
    ADD CONSTRAINT ukeiidawsj9c12638rt32lyrhfi UNIQUE (knowledge_base_id, original_file_name);


--
-- Name: document ukorun0gwdbwprmk9gxqhplaqrc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document
    ADD CONSTRAINT ukorun0gwdbwprmk9gxqhplaqrc UNIQUE (storage_key);


--
-- Name: document_chunk ukpnfch3t1hjgsx82d7q78xqdqu; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_chunk
    ADD CONSTRAINT ukpnfch3t1hjgsx82d7q78xqdqu UNIQUE (document_id, chunk_index);


--
-- Name: membership ukseiejkw0eeiy92my0o7g3pkh3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership
    ADD CONSTRAINT ukseiejkw0eeiy92my0o7g3pkh3 UNIQUE (user_id, organization_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: membership fk7ccx5hs0p61m5wrwywf0q2cdv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership
    ADD CONSTRAINT fk7ccx5hs0p61m5wrwywf0q2cdv FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: document_chunk fkb9p3746t9g2yjp134mgq5pckr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_chunk
    ADD CONSTRAINT fkb9p3746t9g2yjp134mgq5pckr FOREIGN KEY (document_id) REFERENCES public.document(document_id);


--
-- Name: document fkfiqmy10c69fwaq191ydn9scdn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document
    ADD CONSTRAINT fkfiqmy10c69fwaq191ydn9scdn FOREIGN KEY (knowledge_base_id) REFERENCES public.knowledge_base(knowledge_base_id);


--
-- Name: membership fkhelgqr6jj4c3bjc40jmbctmt9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership
    ADD CONSTRAINT fkhelgqr6jj4c3bjc40jmbctmt9 FOREIGN KEY (organization_id) REFERENCES public.organization(organization_id);


--
-- Name: knowledge_base fkhv2mt985g90kuy8gn73wt8tng; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.knowledge_base
    ADD CONSTRAINT fkhv2mt985g90kuy8gn73wt8tng FOREIGN KEY (organization_id) REFERENCES public.organization(organization_id);


--
-- PostgreSQL database dump complete
--


